### PR TITLE
Removed overflow_column argument from constructor

### PR DESCRIPTION
**Pull request by DanielGilB**
Refactor constructor to single argument instead of optional argument with default value.

If you need to edit default overflow column name you can do this:

```php
class MyCustomFormRequest extends OverflowFormRequest
{
    protected $overflow_column = "my_custom_column_name";

    public function __construct()
    {
        parent::__construct(new MyCustomModel);
    }
}

```

### CODE REVIEW

**Comment by CraftLogan** [comment]
@DanielGilB Nice, refactor! I have also added in a Macro to extend the standard Illimunate request so you can still use overflow without creating a custom form request. The syntax for that is 

`$request->overflow(new Model);`

I am also getting ready to add another macro for the allWithOverflow() method and the syntax for it will look something like this:

`$request->allWithOverflow(new Model)`


Thank you for all your contributions to this project; it seems to be coming along nicely. Would you like to become a maintainer on this project with me?

**Comment by DanielGilB** [comment]
We would have to choose a road. I like your idea about Macro.

So We need remove old form request and start to develop this way.  Can you do it? After this, Im going to refactor your idea (Its highly coupled), then We could start to define some features.

What do You think?

**Comment by CraftLogan** [comment]
Yeah, so do you think we should go down the Macro route and drop the form request idea entirely? I would be fine either way, leaving the form request or removing the form request. It would be easier to manage the macro codebase, though, and I think it would probably be the most practical and accessible way for developers to use Laravel Overflow. Do you have any features in mind? I think some refactoring would be great to create looser coupling, and it seems you are at a more advanced skill level than I am with architecture so refactor away. I will also add you to the repo so you can merge pull requests. Thank you so much for the help I look forward to working with you. We could also set up a more direct way to chat about the project; if you would like you can send me an email at craftlogan@icloud.com

**Comment by DanielGilB** [comment]
Macro is better option, I think.

First step: remove old form request
Second step: refactors and define MVP
Third step: define features

Thanks, I will write you.

**Pull request merged**
